# Generated by Django 5.1.2 on 2024-10-09 21:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo_Electronico', models.TextField()),
                ('contrasena', models.CharField(max_length=15)),
                ('fecha_Registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('biografia', models.CharField(max_length=200)),
                ('foto_Perfil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguidor', models.CharField(max_length=200)),
                ('seguido', models.CharField(max_length=200)),
                ('usuario', models.ManyToManyField(to='Red_Social.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_Creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Red_Social.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Me_Gusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Red_Social.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_Creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=200)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Red_Social.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Red_Social.usuario')),
            ],
        ),
    ]
